# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='文章标题')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='链接')),
                ('abstract', models.TextField(verbose_name='摘要')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('0', '发布'), ('1', '草稿')], default='0', max_length=1, verbose_name='文章状态')),
            ],
            options={
                'verbose_name_plural': '文章(Article)',
                'ordering': ['-created_time'],
                'verbose_name': '文章(Article)',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='分类名称')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('description', models.CharField(max_length=32, verbose_name='描述')),
                ('keywords', models.CharField(max_length=255, verbose_name='关键词')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '分类(Categories)',
                'ordering': ['-created_time'],
                'verbose_name': '分类(Categories)',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='友情链接名字')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name_plural': '友情链接(Links)',
                'ordering': ['id'],
                'verbose_name': '友情链接(Links)',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '标签(Tag)',
                'ordering': ['id'],
                'verbose_name': '标签(Tag)',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categories', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='标签'),
        ),
    ]
