# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='连接'),
        ),
    ]
