# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_categories_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名字')),
                ('avatar', models.CharField(default='static/image/avatar.png', max_length=32, verbose_name='头像地址')),
                ('article', models.IntegerField(verbose_name='文章ID')),
                ('declaration', models.CharField(max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '关于我(About)',
                'verbose_name': '关于我(About)',
            },
        ),
        migrations.CreateModel(
            name='AboutIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=32, verbose_name='图表名称')),
                ('url', models.URLField(max_length=32, verbose_name='连接地址')),
            ],
            options={
                'verbose_name_plural': '关于我小图标(AboutIcon)',
                'verbose_name': '关于我小图标(AboutIcon)',
            },
        ),
    ]
