# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_abouticon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archive',
            new_name='Article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': '文章(Article)', 'verbose_name_plural': '文章(Article)'},
        ),
        migrations.AlterField(
            model_name='about',
            name='avatar',
            field=models.CharField(default='/static/image/avatar.png', max_length=32, verbose_name='头像地址'),
        ),
    ]
