# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161228_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time'], 'verbose_name': '文章(Article)', 'verbose_name_plural': '文章(Article)'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-created_time'], 'verbose_name': '分类(Categories)', 'verbose_name_plural': '分类(Categories)'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='browse',
        ),
    ]
